version: '2'
services:
  influx:
    build: .
    ports:
      - "10003:8086"
    volumes:
      - ${INFLUX_DATA_DIR}:/var/lib/influxdb
      - ${INFLUX_CONFIG_DIR}/influxdb.conf:/etc/influxdb/influxdb.conf
    restart: always
